// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: cat_v1/cat_v1.proto

package cat_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос поглаживания
type PetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Идентификатор кота
}

func (x *PetRequest) Reset() {
	*x = PetRequest{}
	mi := &file_cat_v1_cat_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRequest) ProtoMessage() {}

func (x *PetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cat_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRequest.ProtoReflect.Descriptor instead.
func (*PetRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cat_v1_proto_rawDescGZIP(), []int{0}
}

func (x *PetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Ответ на поглаживание
type PetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mood CatMood `protobuf:"varint,1,opt,name=mood,proto3,enum=cat_v1.CatMood" json:"mood,omitempty"` // Настроение кота
}

func (x *PetResponse) Reset() {
	*x = PetResponse{}
	mi := &file_cat_v1_cat_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetResponse) ProtoMessage() {}

func (x *PetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cat_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetResponse.ProtoReflect.Descriptor instead.
func (*PetResponse) Descriptor() ([]byte, []int) {
	return file_cat_v1_cat_v1_proto_rawDescGZIP(), []int{1}
}

func (x *PetResponse) GetMood() CatMood {
	if x != nil {
		return x.Mood
	}
	return CatMood_MOOD_UNKNOWN
}

// Запрос кормления
type FeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                            // Идентификатор кота
	FoodType string `protobuf:"bytes,2,opt,name=food_type,json=foodType,proto3" json:"food_type,omitempty"` // Тип еды
	Amount   int32  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                    // Количество еды
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	mi := &file_cat_v1_cat_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cat_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cat_v1_proto_rawDescGZIP(), []int{2}
}

func (x *FeedRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FeedRequest) GetFoodType() string {
	if x != nil {
		return x.FoodType
	}
	return ""
}

func (x *FeedRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Ответ на кормление
type FeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reaction FeedReaction `protobuf:"varint,1,opt,name=reaction,proto3,enum=cat_v1.FeedReaction" json:"reaction,omitempty"` // Реакция кота
}

func (x *FeedResponse) Reset() {
	*x = FeedResponse{}
	mi := &file_cat_v1_cat_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResponse) ProtoMessage() {}

func (x *FeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cat_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResponse.ProtoReflect.Descriptor instead.
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return file_cat_v1_cat_v1_proto_rawDescGZIP(), []int{3}
}

func (x *FeedResponse) GetReaction() FeedReaction {
	if x != nil {
		return x.Reaction
	}
	return FeedReaction_REACTION_UNKNOWN
}

// Запрос на открытие двери
type OpenDoorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // Идентификатор кота
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"` // Куда кот хочет выйти
}

func (x *OpenDoorRequest) Reset() {
	*x = OpenDoorRequest{}
	mi := &file_cat_v1_cat_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDoorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDoorRequest) ProtoMessage() {}

func (x *OpenDoorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cat_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDoorRequest.ProtoReflect.Descriptor instead.
func (*OpenDoorRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cat_v1_proto_rawDescGZIP(), []int{4}
}

func (x *OpenDoorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OpenDoorRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

// Ответ на открытие двери
type OpenDoorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DoorStatus `protobuf:"varint,2,opt,name=status,proto3,enum=cat_v1.DoorStatus" json:"status,omitempty"` // Текущий статус
}

func (x *OpenDoorResponse) Reset() {
	*x = OpenDoorResponse{}
	mi := &file_cat_v1_cat_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDoorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDoorResponse) ProtoMessage() {}

func (x *OpenDoorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cat_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDoorResponse.ProtoReflect.Descriptor instead.
func (*OpenDoorResponse) Descriptor() ([]byte, []int) {
	return file_cat_v1_cat_v1_proto_rawDescGZIP(), []int{5}
}

func (x *OpenDoorResponse) GetStatus() DoorStatus {
	if x != nil {
		return x.Status
	}
	return DoorStatus_DOOR_UNKNOWN
}

var File_cat_v1_cat_v1_proto protoreflect.FileDescriptor

var file_cat_v1_cat_v1_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x61, 0x74,
	0x5f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x0a, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x0b, 0x50, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x4d, 0x6f,
	0x6f, 0x64, 0x52, 0x04, 0x6d, 0x6f, 0x6f, 0x64, 0x22, 0x52, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x0c,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43,
	0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x6f, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31,
	0x2e, 0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x32, 0x82, 0x02, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4b, 0x0a, 0x03, 0x50, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x63, 0x61, 0x74, 0x5f,
	0x76, 0x31, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x61, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x2f, 0x70, 0x65, 0x74, 0x12,
	0x4a, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x13, 0x2e, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31,
	0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63,
	0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22, 0x0c, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x61, 0x74, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x12, 0x5b, 0x0a, 0x08, 0x4f,
	0x70, 0x65, 0x6e, 0x44, 0x6f, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x6f,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x16, 0x3a, 0x01, 0x2a, 0x22, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x74, 0x2f, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x63, 0x76, 0x39, 0x31, 0x31, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x3b, 0x63, 0x61, 0x74, 0x5f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cat_v1_cat_v1_proto_rawDescOnce sync.Once
	file_cat_v1_cat_v1_proto_rawDescData = file_cat_v1_cat_v1_proto_rawDesc
)

func file_cat_v1_cat_v1_proto_rawDescGZIP() []byte {
	file_cat_v1_cat_v1_proto_rawDescOnce.Do(func() {
		file_cat_v1_cat_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_cat_v1_cat_v1_proto_rawDescData)
	})
	return file_cat_v1_cat_v1_proto_rawDescData
}

var file_cat_v1_cat_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cat_v1_cat_v1_proto_goTypes = []any{
	(*PetRequest)(nil),       // 0: cat_v1.PetRequest
	(*PetResponse)(nil),      // 1: cat_v1.PetResponse
	(*FeedRequest)(nil),      // 2: cat_v1.FeedRequest
	(*FeedResponse)(nil),     // 3: cat_v1.FeedResponse
	(*OpenDoorRequest)(nil),  // 4: cat_v1.OpenDoorRequest
	(*OpenDoorResponse)(nil), // 5: cat_v1.OpenDoorResponse
	(CatMood)(0),             // 6: cat_v1.CatMood
	(FeedReaction)(0),        // 7: cat_v1.FeedReaction
	(DoorStatus)(0),          // 8: cat_v1.DoorStatus
}
var file_cat_v1_cat_v1_proto_depIdxs = []int32{
	6, // 0: cat_v1.PetResponse.mood:type_name -> cat_v1.CatMood
	7, // 1: cat_v1.FeedResponse.reaction:type_name -> cat_v1.FeedReaction
	8, // 2: cat_v1.OpenDoorResponse.status:type_name -> cat_v1.DoorStatus
	0, // 3: cat_v1.CatService.Pet:input_type -> cat_v1.PetRequest
	2, // 4: cat_v1.CatService.Feed:input_type -> cat_v1.FeedRequest
	4, // 5: cat_v1.CatService.OpenDoor:input_type -> cat_v1.OpenDoorRequest
	1, // 6: cat_v1.CatService.Pet:output_type -> cat_v1.PetResponse
	3, // 7: cat_v1.CatService.Feed:output_type -> cat_v1.FeedResponse
	5, // 8: cat_v1.CatService.OpenDoor:output_type -> cat_v1.OpenDoorResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cat_v1_cat_v1_proto_init() }
func file_cat_v1_cat_v1_proto_init() {
	if File_cat_v1_cat_v1_proto != nil {
		return
	}
	file_cat_v1_cat_v1_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cat_v1_cat_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cat_v1_cat_v1_proto_goTypes,
		DependencyIndexes: file_cat_v1_cat_v1_proto_depIdxs,
		MessageInfos:      file_cat_v1_cat_v1_proto_msgTypes,
	}.Build()
	File_cat_v1_cat_v1_proto = out.File
	file_cat_v1_cat_v1_proto_rawDesc = nil
	file_cat_v1_cat_v1_proto_goTypes = nil
	file_cat_v1_cat_v1_proto_depIdxs = nil
}
